### ISSUE TITLE
FeatureRequest: Generate a Unit Test for Every Property

### ISSUE THREAD

**Issue by monksy** [josefbetancourt/property-asserter#1]
This would be nice to extend JUnit to automatically generate a unit test for every property. This would allow for the identification of the unit tests performed (wither they were passed or failed)

**Comment by josefbetancourt** [comment]
Yes, that is what the property-asserter class allows.

**Comment by monksy** [comment]
Sorry, but I forgot to mention that this was the case in the GlazedList
plugin in the EventTableModel. A search of the properties only looks for
those that have a setter method.

2014-09-28 23:05 GMT-05:00 josefbetancourt notifications@github.com:
